//source: HuggingFaceH4/code_evaluation_prompts
const prompts = [
    "Write a Python function called add_numbers that takes two arguments a and b, and returns their sum.",
    "Write a Python function called add_numbers that takes two arguments a and b, and returns their sum.",
    "Write a Python program that prompts the user to enter their name, and then prints a greeting with their name.",
    "Write a Python program that prompts the user to enter their name, and then prints a greeting with their name.",
    "Write a Python function called calculate_area that takes two arguments width and height, and returns the area of a rectangle with those dimensions.",
    "Write a Python function called calculate_area that takes two arguments width and height, and returns the area of a rectangle with those dimensions.",
    "Write a Python program that reads in a list of numbers from the user, and then prints the sum of those numbers.",
    "Write a Python program that reads in a list of numbers from the user, and then prints the sum of those numbers.",
    "Write a Python function called count_vowels that takes a string as its argument and returns the number of vowels in the string.",
    "Write a Python function called count_vowels that takes a string as its argument and returns the number of vowels in the string.",
    "Write a Python program that reads in a text file, counts the number of words in the file, and prints the result.",
    "Write a Python program that reads in a text file, counts the number of words in the file, and prints the result.",
    "Write a Python function called factorial that takes a positive integer as its argument and returns the factorial of that integer.",
    "Write a Python function called factorial that takes a positive integer as its argument and returns the factorial of that integer.",
    "Write a Python program that generates a random number between 1 and 100, and prompts the user to guess the number until they get it right.",
    "Write a Python program that generates a random number between 1 and 100, and prompts the user to guess the number until they get it right.",
    "Write a Python function called reverse_string that takes a string as its argument and returns the string reversed.",
    "Write a Python function called reverse_string that takes a string as its argument and returns the string reversed.",
    "Write a Python program that reads in a list of integers from the user, and then prints the maximum and minimum values in the list.",
    "Write a Python program that reads in a list of integers from the user, and then prints the maximum and minimum values in the list.",
    "Write a Python program that prompts the user to enter their age, and then prints a message telling them whether they are old enough to vote or not.",
    "Write a Python program that prompts the user to enter their age, and then prints a message telling them whether they are old enough to vote or not.",
    "Write a Python function called is_palindrome that takes a string as its argument and returns True if the string is a palindrome (reads the same backward as forward), and False otherwise.",
    "Write a Python function called is_palindrome that takes a string as its argument and returns True if the string is a palindrome (reads the same backward as forward), and False otherwise.",
    "Write a Python program that reads in a list of strings from the user, and then prints the longest and shortest strings in the list.",
    "Write a Python program that reads in a list of strings from the user, and then prints the longest and shortest strings in the list.",
    "Write a Python function called find_maximum that takes a list of numbers as its argument and returns the maximum value in the list.",
    "Write a Python function called find_maximum that takes a list of numbers as its argument and returns the maximum value in the list.",
    "Write a Python program that reads in a list of integers from the user, and then prints the sum of the even integers in the list.",
    "Write a Python program that reads in a list of integers from the user, and then prints the sum of the even integers in the list.",
    "Write a Python function called binary_search that takes a sorted list of numbers and a target value as its arguments, and returns the index of the target value in the list (or -1 if the target value is not in the list).",
    "Write a Python function called binary_search that takes a sorted list of numbers and a target value as its arguments, and returns the index of the target value in the list (or -1 if the target value is not in the list).",
    "Write a Python program that reads in a list of numbers from the user, and then prints a new list with only the unique values from the original list.",
    "Write a Python program that reads in a list of numbers from the user, and then prints a new list with only the unique values from the original list.",
    "Write a Python function called remove_duplicates that takes a list as its argument and returns a new list with only the unique values from the original list.",
    "Write a Python function called remove_duplicates that takes a list as its argument and returns a new list with only the unique values from the original list.",
    "Write a Python program that prompts the user to enter a string, and then prints a message telling them whether the string contains only digits or not.",
    "Write a Python program that prompts the user to enter a string, and then prints a message telling them whether the string contains only digits or not.",
    "Write a Python function called linear_regression that takes two lists x and y as its arguments, and returns the slope and y-intercept of the least squares regression line for the data.",
    "Write a Python function called linear_regression that takes two lists x and y as its arguments, and returns the slope and y-intercept of the least squares regression line for the data.",
    "Write a Python function called permutations that takes a string as its argument and returns a list of all possible permutations of the characters in the string.",
    "Write a Python function called permutations that takes a string as its argument and returns a list of all possible permutations of the characters in the string.",
    "Write a Python program that reads in a list of words from a text file, and then prints the top 10 most frequently occurring words in the file (excluding common stop words like 'the', 'and', 'a', etc.).",
    "Write a Python program that reads in a list of words from a text file, and then prints the top 10 most frequently occurring words in the file (excluding common stop words like 'the', 'and', 'a', etc.).",
    "Write a Python function called n_choose_k that takes two integers n and k as its arguments and returns the number of ways to choose k items from a set of n items (i.e. the binomial coefficient).",
    "Write a Python function called n_choose_k that takes two integers n and k as its arguments and returns the number of ways to choose k items from a set of n items (i.e. the binomial coefficient).",
    "Write a Python program that reads in a list of integers from a text file, and then prints the length of the longest increasing subsequence in the list.",
    "Write a Python program that reads in a list of integers from a text file, and then prints the length of the longest increasing subsequence in the list.",
    "Write a Python function called is_prime that takes an integer as its argument and returns True if the integer is prime, and False otherwise.",
    "Write a Python function called is_prime that takes an integer as its argument and returns True if the integer is prime, and False otherwise.",
    "Write a Python program that reads in a list of numbers from the user, and then prints the median value in the list.",
    "Write a Python program that reads in a list of numbers from the user, and then prints the median value in the list.",
    "Write a Python function called closest_pair that takes a list of points (represented as tuples of (x, y) coordinates) as its argument, and returns the pair of points with the smallest distance between them.",
    "Write a Python function called closest_pair that takes a list of points (represented as tuples of (x, y) coordinates) as its argument, and returns the pair of points with the smallest distance between them.",
    "Write a Python program that reads in a list of strings from the user, and then prints a new list with only the strings that are anagrams of each other.",
    "Write a Python program that reads in a list of strings from the user, and then prints a new list with only the strings that are anagrams of each other.",
    "Write a Python function called levenshtein_distance that takes two strings as its arguments and returns the Levenshtein distance between them (i.e. the minimum number of single-character edits required to transform one string into the other).",
    "Write a Python function called levenshtein_distance that takes two strings as its arguments and returns the Levenshtein distance between them (i.e. the minimum number of single-character edits required to transform one string into the other).",
    "Write a Python program that reads in a list of integers from the user, and then prints the length of the longest subarray of consecutive integers in the list (i.e. a sequence of integers with no gaps between them).",
    "Write a Python program that reads in a list of integers from the user, and then prints the length of the longest subarray of consecutive integers in the list (i.e. a sequence of integers with no gaps between them).",
    "Write a Python program that implements a binary search algorithm to find the index of a target value in a sorted list. If the target value is not present in the list, return -1.",
    "Write a Python program that implements a binary search algorithm to find the index of a target value in a sorted list. If the target value is not present in the list, return -1.",
    "Write a Python class called Matrix that represents a 2-dimensional matrix. Implement methods to perform matrix addition, subtraction, and multiplication. Include a method to transpose the matrix as well.",
    "Write a Python class called Matrix that represents a 2-dimensional matrix. Implement methods to perform matrix addition, subtraction, and multiplication. Include a method to transpose the matrix as well.",
    "Write a Python program that reads in a text file and counts the frequency of each word in the file. Print the top 5 most frequently occurring words and their counts.",
    "Write a Python program that reads in a text file and counts the frequency of each word in the file. Print the top 5 most frequently occurring words and their counts.",
    "Write a Python function called prime_factors that takes a positive integer as its argument and returns a list of its prime factors.",
    "Write a Python function called prime_factors that takes a positive integer as its argument and returns a list of its prime factors.",
    "Write a Python program that simulates a game of Tic-Tac-Toe. Implement the logic to check for a win or a tie, and allow two players to take turns entering their moves.",
    "Write a Python program that simulates a game of Tic-Tac-Toe. Implement the logic to check for a win or a tie, and allow two players to take turns entering their moves.",
    "Write a Python function called flatten_list that takes a nested list as its argument and returns a flattened version of the list. For example, given the list [1, [2, [3, 4], 5], 6], the function should return [1, 2, 3, 4, 5, 6].",
    "Write a Python function called flatten_list that takes a nested list as its argument and returns a flattened version of the list. For example, given the list [1, [2, [3, 4], 5], 6], the function should return [1, 2, 3, 4, 5, 6].",
    "Write a Python program that reads in a CSV file and calculates the average of a specific column. Prompt the user to enter the column number and print the average value.",
    "Write a Python program that reads in a CSV file and calculates the average of a specific column. Prompt the user to enter the column number and print the average value.",
    "Write a Python class called BinaryTree that represents a binary tree data structure. Implement methods to insert a node, search for a value, and perform a preorder traversal of the tree.",
    "Write a Python class called BinaryTree that represents a binary tree data structure. Implement methods to insert a node, search for a value, and perform a preorder traversal of the tree.",
    "Write a Python program that reads in a list of words and finds the longest common prefix among them. If there is no common prefix, print 'No common prefix'.",
    "Write a Python program that reads in a list of words and finds the longest common prefix among them. If there is no common prefix, print 'No common prefix'.",
    "Write a Python function called permutations that takes a list of elements and returns a list of all possible permutations of those elements.",
    "Write a Python function called permutations that takes a list of elements and returns a list of all possible permutations of those elements.",
    "Write a Python function called primes_under_n that takes a positive integer n as its argument and returns a list of all prime numbers less than n. Use the Sieve of Eratosthenes algorithm to optimize the computation.",
    "Write a Python function called primes_under_n that takes a positive integer n as its argument and returns a list of all prime numbers less than n. Use the Sieve of Eratosthenes algorithm to optimize the computation.",
    "Write a Python program that reads in a list of integers from the user, and then finds the longest increasing subsequence in the list. Print the subsequence and its length.",
    "Write a Python program that reads in a list of integers from the user, and then finds the longest increasing subsequence in the list. Print the subsequence and its length.",
    "Write a Python function called n_choose_k that takes two non-negative integers n and k as its arguments and returns the number of ways to choose k items from a set of n items. Use dynamic programming to optimize the computation.",
    "Write a Python function called n_choose_k that takes two non-negative integers n and k as its arguments and returns the number of ways to choose k items from a set of n items. Use dynamic programming to optimize the computation.",
    "Write a Python program that reads in a list of words and finds the longest word that can be made by concatenating other words in the list. Print the longest word and the words that were used to make it.",
    "Write a Python program that reads in a list of words and finds the longest word that can be made by concatenating other words in the list. Print the longest word and the words that were used to make it.",
    "Write a Python class called LRUCache that implements a least recently used (LRU) cache. The cache should have a fixed capacity, and should automatically evict the least recently used item when the cache is full.",
    "Write a Python class called LRUCache that implements a least recently used (LRU) cache. The cache should have a fixed capacity, and should automatically evict the least recently used item when the cache is full.",
    "Write a Python program that reads in a text file and generates a word cloud visualization of the most frequently occurring words. Use a Python package such as wordcloud or matplotlib to create the visualization.",
    "Write a Python program that reads in a text file and generates a word cloud visualization of the most frequently occurring words. Use a Python package such as wordcloud or matplotlib to create the visualization.",
    "Write a Python function called find_median that takes two sorted lists a and b of equal length as its arguments and returns the median value of the merged lists. Use a divide-and-conquer algorithm to optimize the computation.",
    "Write a Python function called find_median that takes two sorted lists a and b of equal length as its arguments and returns the median value of the merged lists. Use a divide-and-conquer algorithm to optimize the computation.",
    "Write a Python program that reads in a list of words and a target word, and then finds the shortest path between the target word and any other word in the list by changing one letter at a time. Print the path and its length.",
    "Write a Python program that reads in a list of words and a target word, and then finds the shortest path between the target word and any other word in the list by changing one letter at a time. Print the path and its length.",
    "Write a Python function called count_inversions that takes a list of integers as its argument and returns the number of inversions in the list. An inversion is a pair of elements (i, j) such that i < j and a[i] > a[j].",
    "Write a Python function called count_inversions that takes a list of integers as its argument and returns the number of inversions in the list. An inversion is a pair of elements (i, j) such that i < j and a[i] > a[j].",
    "Write a Python program that implements a k-means clustering algorithm to cluster a set of data points into k clusters. Use a Python package such as scikit-learn to perform the clustering.",
    "Write a Python program that implements a k-means clustering algorithm to cluster a set of data points into k clusters. Use a Python package such as scikit-learn to perform the clustering.",
    "Write a C++ program to find the maximum and minimum elements of an array of integers. The program should take the array as input from the user, and print the maximum and minimum elements to the console.",
    "Write a C++ program to find the maximum and minimum elements of an array of integers. The program should take the array as input from the user, and print the maximum and minimum elements to the console.",
    "Write a C++ program to implement a linked list data structure. The program should allow the user to insert and delete nodes from the list, and should print the contents of the list to the console after each operation.",
    "Write a C++ program to implement a linked list data structure. The program should allow the user to insert and delete nodes from the list, and should print the contents of the list to the console after each operation.",
    "Write a C++ program to compute the greatest common divisor (GCD) of two integers using the Euclidean algorithm. The program should take the two integers as input from the user, and print the GCD to the console.",
    "Write a C++ program to compute the greatest common divisor (GCD) of two integers using the Euclidean algorithm. The program should take the two integers as input from the user, and print the GCD to the console.",
    "Write a C++ program to implement a binary search tree data structure. The program should allow the user to insert and delete nodes from the tree, and should print the contents of the tree to the console after each operation.",
    "Write a C++ program to implement a binary search tree data structure. The program should allow the user to insert and delete nodes from the tree, and should print the contents of the tree to the console after each operation.",
    "Write a C++ program to implement a hash table data structure using linear probing. The program should allow the user to insert and retrieve elements from the hash table, and should print the contents of the table to the console after each operation.",
    "Write a C++ program to implement a hash table data structure using linear probing. The program should allow the user to insert and retrieve elements from the hash table, and should print the contents of the table to the console after each operation.",
    "Write a C++ program to compute the value of pi using the Monte Carlo method. The program should take the number of iterations as input from the user, and print the estimated value of pi to the console.",
    "Write a C++ program to compute the value of pi using the Monte Carlo method. The program should take the number of iterations as input from the user, and print the estimated value of pi to the console.",
    "Write a C++ program to implement a binary heap data structure. The program should allow the user to insert and extract elements from the heap, and should print the contents of the heap to the console after each operation.",
    "Write a C++ program to implement a binary heap data structure. The program should allow the user to insert and extract elements from the heap, and should print the contents of the heap to the console after each operation.",
    "Write a C++ program to implement the quicksort algorithm. The program should take an array of integers as input from the user, and should print the sorted array to the console.",
    "Write a C++ program to implement the quicksort algorithm. The program should take an array of integers as input from the user, and should print the sorted array to the console.",
    "Write a C++ program to implement the mergesort algorithm. The program should take an array of integers as input from the user, and should print the sorted array to the console.",
    "Write a C++ program to implement the mergesort algorithm. The program should take an array of integers as input from the user, and should print the sorted array to the console.",
    "Write a C++ program to implement the binary search algorithm using a recursive function. The program should take a sorted array of integers and a target integer as input from the user, and should print whether or not the target integer is in the array to the console.",
    "Write a C++ program to implement the binary search algorithm using a recursive function. The program should take a sorted array of integers and a target integer as input from the user, and should print whether or not the target integer is in the array to the console.",
    "Write a C++ program to compute the sum of two integers. The program should take the two integers as input from the user, and print the sum to the console.",
    "Write a C++ program to compute the sum of two integers. The program should take the two integers as input from the user, and print the sum to the console.",
    "Write a C++ program to compute the factorial of a given integer. The program should take the integer as input from the user, and print the factorial to the console.",
    "Write a C++ program to compute the factorial of a given integer. The program should take the integer as input from the user, and print the factorial to the console.",
    "Write a C++ program to check if a given string is a palindrome. The program should take the string as input from the user, and print whether or not it is a palindrome to the console.",
    "Write a C++ program to check if a given string is a palindrome. The program should take the string as input from the user, and print whether or not it is a palindrome to the console.",
    "Write a C++ program to sort an array of integers in ascending order using the bubble sort algorithm. The program should take the array as input from the user, and print the sorted array to the console.",
    "Write a C++ program to sort an array of integers in ascending order using the bubble sort algorithm. The program should take the array as input from the user, and print the sorted array to the console.",
    "Write a C++ program to implement a binary search algorithm. The program should take a sorted array of integers and a target integer as input from the user, and print whether or not the target integer is in the array to the console.",
    "Write a C++ program to implement a binary search algorithm. The program should take a sorted array of integers and a target integer as input from the user, and print whether or not the target integer is in the array to the console.",
    "Write a C++ program to compute the nth Fibonacci number using recursion. The program should take the value of n as input from the user, and print the nth Fibonacci number to the console.",
    "Write a C++ program to compute the nth Fibonacci number using recursion. The program should take the value of n as input from the user, and print the nth Fibonacci number to the console.",
    "Write a C++ program to compute the sum of the elements of a 2D array. The program should take the 2D array as input from the user, and print the sum to the console.",
    "Write a C++ program to compute the sum of the elements of a 2D array. The program should take the 2D array as input from the user, and print the sum to the console.",
    "Write a C++ program to implement a stack data structure using an array. The program should allow the user to push and pop elements from the stack, and should print the contents of the stack to the console after each operation.",
    "Write a C++ program to implement a stack data structure using an array. The program should allow the user to push and pop elements from the stack, and should print the contents of the stack to the console after each operation.",
    "Write a C++ program to implement a queue data structure using a linked list. The program should allow the user to enqueue and dequeue elements from the queue, and should print the contents of the queue to the console after each operation.",
    "Write a C++ program to implement a queue data structure using a linked list. The program should allow the user to enqueue and dequeue elements from the queue, and should print the contents of the queue to the console after each operation.",
    "Write a C++ program to implement a binary tree data structure. The program should allow the user to insert and delete nodes from the tree, and should print the contents of the tree to the console after each operation.",
    "Write a C++ program to implement a binary tree data structure. The program should allow the user to insert and delete nodes from the tree, and should print the contents of the tree to the console after each operation."
]

export function getRandomPrompt(): string {
    return prompts[Math.floor(Math.random() * prompts.length)];
}